### ISSUE TITLE
Ubuntu 18.04: crash libQt5Gui when accessing Media -> Open File

### ISSUE THREAD

**Issue by marcosps** [flathub/org.videolan.VLC#38]
```
flatpak --version
Flatpak 0.11.7
```

Using flatpak from @alexlarsson ppa:
`http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu bionic main`

After starting VLC, click in Media -> Open File: Crash:

```
flatpak run org.videolan.VLC 
VLC media player 3.0.3 Vetinari (revision 3.0.2-225-gc9e3360dd4)
[0000000000a5df00] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
[0000000000aeb2c0] main playlist: playlist is empty
```

It seems hat Qt5 is crashing:

```
Jun 02 17:08:40 Swordfish systemd[2521]: Started flatpak-org.videolan.VLC-5879.scope.
Jun 02 17:08:40 Swordfish /usr/lib/gdm3/gdm-x-session[2556]: Using O_TMPFILE
Jun 02 17:08:42 Swordfish /usr/lib/gdm3/gdm-x-session[2556]: Using O_TMPFILE
Jun 02 17:08:44 Swordfish kernel: vlc[5893]: segfault at 0 ip 00007f1962f8c4ea sp 00007f196c1cd4d8 error 4 in libQt5Gui.so.5.11.0[7f1962e3f000+57b000]
```

Let me know if you need more info.

**Comment by ahayzen** [comment]
I see the same issue on Ubuntu 18.04, flatpak 0.11.7 (not from PPA, but archive). Running with gdb i was able to extract this info if useful.

```
Thread 5 "vlc" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 15]
0x00007fffed3374ea in QFileDialogOptions::fileMode() const () from /lib/libQt5Gui.so.5
(gdb) bt
#0  0x00007fffed3374ea in QFileDialogOptions::fileMode() const () at /lib/libQt5Gui.so.5
#1  0x00007fffe00258f6 in  () at /usr/lib/plugins/platformthemes/libqgtk3.so
#2  0x00007fffe00272b9 in  () at /usr/lib/plugins/platformthemes/libqgtk3.so
#3  0x00007fffe00272ed in  () at /usr/lib/plugins/platformthemes/libqgtk3.so
#4  0x00007fffe00756fd in  () at /usr/lib/plugins/platformthemes/libqflatpak.so
#5  0x00007fffedb1f350 in QFileDialog::selectFile(QString const&) () at /lib/libQt5Widgets.so.5
#6  0x00007fffedb273fc in QFileDialog::QFileDialog(QFileDialogArgs const&) () at /lib/libQt5Widgets.so.5
#7  0x00007fffedb2785c in QFileDialog::getOpenFileUrls(QWidget*, QString const&, QUrl const&, QString const&, QString*, QFlags<QFileDialog::Option>, QStringList const&) () at /lib/libQt5Widgets.so.5
#8  0x00007fffedf6c0d8 in  () at /app/lib/vlc/plugins/gui/libqt_plugin.so
#9  0x00007fffedf6e0c6 in  () at /app/lib/vlc/plugins/gui/libqt_plugin.so
#10 0x00007fffedf6f1ae in  () at /app/lib/vlc/plugins/gui/libqt_plugin.so
#11 0x00007fffee0b0a2d in  () at /app/lib/vlc/plugins/gui/libqt_plugin.so
#12 0x00007fffecf68553 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/libQt5Core.so.5
#13 0x00007fffecf6891b in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()
    at /lib/libQt5Core.so.5
#14 0x00007fffed8dba74 in QAction::triggered(bool) () at /lib/libQt5Widgets.so.5
#15 0x00007fffed8deaf1 in QAction::activate(QAction::ActionEvent) () at /lib/libQt5Widgets.so.5
#16 0x00007fffeda978aa in  () at /lib/libQt5Widgets.so.5
#17 0x00007fffeda9f976 in  () at /lib/libQt5Widgets.so.5
#18 0x00007fffedaa0651 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /lib/libQt5Widgets.so.5
#19 0x00007fffed92cdc2 in QWidget::event(QEvent*) () at /lib/libQt5Widgets.so.5
#20 0x00007fffedaa2b01 in QMenu::event(QEvent*) () at /lib/libQt5Widgets.so.5
#21 0x00007fffed8e400d in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/libQt5Widgets.so.5
#22 0x00007fffed8ec09b in QApplication::notify(QObject*, QEvent*) () at /lib/libQt5Widgets.so.5
#23 0x00007fffecf381da in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/libQt5Core.so.5
#24 0x00007fffed8eadb9 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /lib/libQt5Widgets.so.5
#25 0x00007fffed9497d5 in  () at /lib/libQt5Widgets.so.5
#26 0x00007fffed94cd59 in  () at /lib/libQt5Widgets.so.5
#27 0x00007fffed8e400d in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/libQt5Widgets.so.5
#28 0x00007fffed8ebb9e in QApplication::notify(QObject*, QEvent*) () at /lib/libQt5Widgets.so.5
#29 0x00007fffecf381da in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/libQt5Core.so.5
#30 0x00007fffed30145b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/libQt5Gui.so.5
#31 0x00007fffed302dd8 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/libQt5Gui.so.5
#32 0x00007fffed2d83fb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQt5Gui.so.5
#33 0x00007fffe1a76c91 in  () at /lib/libQt5XcbQpa.so.5
#34 0x00007fffecf361f9 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib/libQt5Core.so.5
#35 0x00007fffecf3663f in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib/libQt5Core.so.5
#36 0x00007fffecf40344 in QCoreApplication::exec() () at /lib/libQt5Core.so.5
#37 0x00007fffed2f7eac in QGuiApplication::exec() () at /lib/libQt5Gui.so.5
#38 0x00007fffed8e3e9f in QApplication::exec() () at /lib/libQt5Widgets.so.5
#39 0x00007fffedf4dd6c in  () at /app/lib/vlc/plugins/gui/libqt_plugin.so
#40 0x00007fffedf4e893 in  () at /app/lib/vlc/plugins/gui/libqt_plugin.so
#41 0x0000003131007444 in  () at /lib/libpthread.so.0
#42 0x00000031308e827f in clone () at /lib/libc.so.6
(gdb) info threads
  Id   Target Id         Frame 
  1    LWP 8 "vlc"       0x00000031310113b7 in ?? () from /lib/libpthread.so.0
  2    LWP 12 "threaded-ml" 0x00000031308df56d in poll () from /lib/libc.so.6
  3    LWP 13 "vlc"      0x000000313100d353 in pthread_cond_wait () from /lib/libpthread.so.0
  4    LWP 14 "vlc"      0x00000031308df56d in poll () from /lib/libc.so.6
* 5    LWP 15 "vlc"      0x00007fffed3374ea in QFileDialogOptions::fileMode() const ()
   from /lib/libQt5Gui.so.5
  6    LWP 16 "QXcbEventReader" 0x00000031308df56d in poll () from /lib/libc.so.6
  7    LWP 17 "QDBusConnection" 0x00000031308df56d in poll () from /lib/libc.so.6
  8    LWP 18 "vlc"      0x000000313100d353 in pthread_cond_wait () from /lib/libpthread.so.0
  9    LWP 19 "gmain"    0x00000031308df56d in poll () from /lib/libc.so.6
  10   LWP 20 "pool"     0x00000031308e39b9 in syscall () from /lib/libc.so.6
  11   LWP 21 "pool"     0x00000031308e39b9 in syscall () from /lib/libc.so.6
  12   LWP 22 "pool"     0x00000031308e39b9 in syscall () from /lib/libc.so.6
  13   LWP 23 "gdbus"    0x00000031308df56d in poll () from /lib/libc.so.6
  14   LWP 24 "pool"     0x00000031308e39b9 in syscall () from /lib/libc.so.6
  15   LWP 25 "pool"     0x00000031308e39b9 in syscall () from /lib/libc.so.6
  16   LWP 26 "pool"     0x00000031308e39b9 in syscall () from /lib/libc.so.6
  17   LWP 27 "pool"     0x00000031308e39b9 in syscall () from /lib/libc.so.6
  18   LWP 28 "pool"     0x00000031308e39b9 in syscall () from /lib/libc.so.6
```

**Comment by Enaunimes** [comment]
Same case on Fedora 28 Workstation. Before [this commit](https://github.com/flathub/org.videolan.VLC/commit/91f322141b1a76238ddaf7dfb5cbe4b590f40ead) it worked fine.

**Comment by marcosps** [comment]
With today update of kde platform, Open FIle does not crash anymore, but it does not open either.

**Comment by marcosps** [comment]
Fixed in my last flatpak update. Thanks for taking a look at it :)
